[build]
  command = "yarn run build"
  publish = "/public"


[context.deploy-preview]
  command = "yarn docs:build"
  publish = "blog/.vuepress/dist"
  environment = { NODE_ENV = "master" }
  base = "/"
  preview_path = "https://hitowa-test-cms.netlify.app/preview"