[build]
  command = "yarn run build"
  publish = "docs/.vuepress/dist"


[context.deploy-preview]
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"
  environment = { NODE_ENV = "production" }
  base = "/"
  [[redirects]]
  from = "*"
  to = "/index.html"
  status = 200
  preview_path = "https://hitowa-test-cms.netlify.app/docs"